common: &common
  adapter: postgresql
  username: pochour
  # password: password # from psql setup, see Postgresql

development:
  <<: *common
  database: pochour_development

test:
  <<: *common
  database: pochour_test

production:
  <<: *common
  database: pochour_production